/*
 * File: app/view/Contactos.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactosAlegra.view.Contactos', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.contactos',

    requires: [
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column'
    ],

    height: 250,
    id: 'ViewContactosId',
    itemId: 'ViewContactosItemId',
    width: 1000,
    title: 'Contactos',

    items: [
        {
            xtype: 'button',
            itemId: 'BtAddContacto',
            allowDepress: false,
            iconCls: 'x-fa fa-plus',
            text: 'Nuevo Contacto'
        },
        {
            xtype: 'gridpanel',
            itemId: 'GridContactos',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 250,
                    dataIndex: 'nombre',
                    text: 'Nombre'
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'identificacion',
                    text: 'Identificacion'
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'telefono1',
                    text: 'Telefono1'
                },
                {
                    xtype: 'gridcolumn',
                    width: 250,
                    dataIndex: 'observaciones',
                    text: 'Observaciones'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Acciones',
                    text: 'Acciones'
                }
            ]
        }
    ]

});