/*
 * File: app/view/NuevoContacto.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactosAlegra.view.NuevoContacto', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.nuevocontacto',

    requires: [
        'ContactosAlegra.view.NuevoContactoViewModel',
        'Ext.form.field.ComboBox',
        'Ext.panel.Panel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'nuevocontacto'
    },
    height: 200,
    id: 'ViewNuevoContactoId',
    itemId: 'ViewNuevoContactoItemId',
    width: 800,
    layout: 'column',
    iconCls: 'x-fa fa-plus',
    title: 'Nuevo Contacto',

    items: [
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Nombre',
            labelAlign: 'right',
            labelWidth: 110
        },
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Identificación',
            labelAlign: 'right',
            labelWidth: 110
        },
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Dirección',
            labelAlign: 'right',
            labelWidth: 110
        },
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Correo electrónico',
            labelAlign: 'right',
            labelWidth: 110
        },
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Teléfono 1',
            labelAlign: 'right',
            labelWidth: 110
        },
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Teléfono 2',
            labelAlign: 'right',
            labelWidth: 110
        },
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Fax',
            labelAlign: 'right',
            labelWidth: 110
        },
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Celular',
            labelAlign: 'right',
            labelWidth: 110
        },
        {
            xtype: 'combobox',
            width: 350,
            fieldLabel: 'Lista de Precios',
            labelAlign: 'right',
            labelWidth: 110,
            editable: false,
            queryMode: 'local',
            store: [
                [
                    '0',
                    'General'
                ],
                [
                    '1',
                    'Ninguna'
                ]
            ]
        },
        {
            xtype: 'combobox',
            width: 350,
            fieldLabel: 'Vendedor',
            labelAlign: 'right',
            labelWidth: 110,
            editable: false,
            queryMode: 'local',
            store: [
                [
                    '0',
                    'Ninguno'
                ]
            ]
        },
        {
            xtype: 'combobox',
            width: 350,
            fieldLabel: 'Términos de Pago',
            labelAlign: 'right',
            labelWidth: 110,
            editable: false,
            queryMode: 'local',
            store: [
                [
                    '0',
                    'Vencimiento Manual'
                ],
                [
                    '1',
                    'De Contado'
                ],
                [
                    '2',
                    '8 días'
                ],
                [
                    '3',
                    '15 días'
                ],
                [
                    '4',
                    '30 días'
                ],
                [
                    '5',
                    '60 días'
                ]
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'panel',
            dock: 'bottom',
            items: [
                {
                    xtype: 'button',
                    itemId: 'BtCancelar',
                    width: 150,
                    text: 'Cancelar'
                },
                {
                    xtype: 'button',
                    itemId: 'BtGuardarOtro',
                    width: 150,
                    text: 'Guardar y crear otro'
                },
                {
                    xtype: 'button',
                    itemId: 'BtGuardar',
                    width: 150,
                    text: 'Guardar'
                }
            ]
        }
    ]

});