/*
 * File: app/model/ContactosModel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactosAlegra.model.ContactosModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'nombre'
        },
        {
            name: 'identificacion'
        },
        {
            name: 'email'
        },
        {
            name: 'telefono1'
        },
        {
            name: 'telefono2'
        },
        {
            name: 'fax'
        },
        {
            name: 'celular'
        },
        {
            name: 'observaciones'
        },
        {
            name: 'tipo'
        },
        {
            name: 'direccion'
        },
        {
            name: 'vendedor'
        },
        {
            name: 'terminospago'
        },
        {
            name: 'listaprecio'
        },
        {
            name: 'internalContacts'
        }
    ]
});