/*
 * File: app/controller/ContactoController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactosAlegra.controller.ContactoController', {
    extend: 'Ext.app.Controller',

    refs: {
        RfBtAddContacto: '#BtAddContacto'
    },

    control: {
        "button": {
            click: 'onButtonClick'
        }
    },

    onButtonClick: function(button, e, eOpts) {
                if (button.itemId == "BtAddContacto"){
                    Ext.getCmp('ViewContactosId').hide();
                    Ext.create('ContactosAlegra.view.NuevoContacto', {renderTo: Ext.getBody()});
                }

    }

});
