/*
 * File: app/controller/NuevoContactoController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactosAlegra.controller.NuevoContactoController', {
    extend: 'Ext.app.Controller',

    refs: {
        RfBtCancelar: '#BtCancelar',
        RfBtGuardarOtro: '#BtGuardarOtro',
        RfBtGuardar: '#BtGuardar'
    },

    control: {
        "button": {
            click: 'onButtonClick'
        }
    },

    onButtonClick: function(button, e, eOpts) {
                if (button.itemId == "BtCancelar"){
                    Ext.Msg.confirm("Cancelar", "¿Esta seguro de Cancelar?", function(btnText){

                        if(btnText === "yes"){

                             Ext.getCmp('ViewNuevoContactoId').close();
                             Ext.getCmp('ViewContactosId').show();

                        }

                    }, this);

                }

                if (button.itemId == "BtGuardarOtro"){
                    Ext.Msg.alert('Status', 'hay que guardar y limpiar');

                }

                if (button.itemId == "BtGuardar"){
                     alert("hay que guardar y cerrar");
                     Ext.getCmp('ViewNuevoContactoId').close();
                     Ext.getCmp('ViewContactosId').show();

                }

    }

});
